-- Create database
CREATE DATABASE IF NOT EXISTS affiliate_store;
USE affiliate_store;

-- Products table
CREATE TABLE `products` (
    `id` INT(11) AUTO_INCREMENT PRIMARY KEY,
    `asin` VARCHAR(20) UNIQUE NOT NULL,
    `title` VARCHAR(500) NOT NULL,
    `description` TEXT,
    `price` DECIMAL(10,2),
    `category` VARCHAR(100),
    `subcategory` VARCHAR(100),
    `image_url` VARCHAR(500),
    `product_url` VARCHAR(500),
    `brand` VARCHAR(100),
    `rating` DECIMAL(3,2),
    `review_count` INT(11),
    `feature_1` TEXT,
    `feature_2` TEXT,
    `feature_3` TEXT,
    `last_updated` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_category (category),
    INDEX idx_subcategory (subcategory),
    INDEX idx_price (price),
    INDEX idx_rating (rating),
    INDEX idx_brand (brand)
);

-- Blog posts table (auto-generated by Gemini)
CREATE TABLE `blog_posts` (
    `id` INT(11) AUTO_INCREMENT PRIMARY KEY,
    `title` VARCHAR(500) NOT NULL,
    `slug` VARCHAR(500) UNIQUE NOT NULL,
    `content` LONGTEXT,
    `excerpt` TEXT,
    `featured_image` VARCHAR(500),
    `category` VARCHAR(100),
    `subcategory` VARCHAR(100),
    `post_type` ENUM('roundup', 'comparison', 'buying_guide', 'accessory_guide', 'maintenance') DEFAULT 'roundup',
    `product_asins` TEXT,
    `word_count` INT(11),
    `views` INT(11) DEFAULT 0,
    `is_auto_generated` BOOLEAN DEFAULT FALSE,
    `generated_by` VARCHAR(50) DEFAULT 'gemini',
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_slug (slug),
    INDEX idx_category (category),
    INDEX idx_subcategory (subcategory),
    INDEX idx_post_type (post_type),
    INDEX idx_created (created_at)
);

-- Post-product relationships
CREATE TABLE `post_products` (
    `post_id` INT(11),
    `product_id` INT(11),
    `display_order` INT(11) DEFAULT 0,
    PRIMARY KEY (post_id, product_id),
    FOREIGN KEY (`post_id`) REFERENCES `blog_posts`(`id`) ON DELETE CASCADE,
    FOREIGN KEY (`product_id`) REFERENCES `products`(`id`) ON DELETE CASCADE
);

-- Categories table (dynamically managed)
CREATE TABLE `categories` (
    `id` INT(11) AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) UNIQUE NOT NULL,
    `slug` VARCHAR(100) UNIQUE NOT NULL,
    `amazon_search_index` VARCHAR(100),
    `description` TEXT,
    `hero_image` VARCHAR(500),
    `featured` BOOLEAN DEFAULT FALSE,
    `display_order` INT(11) DEFAULT 0,
    `parent_category` VARCHAR(100),
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    INDEX idx_slug (slug),
    INDEX idx_featured (featured),
    INDEX idx_parent (parent_category)
);

-- Subcategories table
CREATE TABLE `subcategories` (
    `id` INT(11) AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `slug` VARCHAR(100) NOT NULL,
    `category_id` INT(11),
    `description` TEXT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`category_id`) REFERENCES `categories`(`id`) ON DELETE CASCADE,
    UNIQUE KEY unique_category_subcategory (category_id, slug),
    INDEX idx_slug (slug)
);

-- Auto blog queue (for scheduled posts)
CREATE TABLE `auto_blog_queue` (
    `id` INT(11) AUTO_INCREMENT PRIMARY KEY,
    `category` VARCHAR(100),
    `subcategory` VARCHAR(100),
    `keyword` VARCHAR(200),
    `post_type` ENUM('roundup', 'comparison', 'buying_guide', 'accessory_guide', 'maintenance') DEFAULT 'roundup',
    `status` ENUM('pending', 'processing', 'completed', 'failed') DEFAULT 'pending',
    `post_id` INT(11),
    `error_message` TEXT,
    `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `processed_at` TIMESTAMP NULL,
    INDEX idx_status (status),
    INDEX idx_category (category)
);

-- Settings table
CREATE TABLE `settings` (
    `key` VARCHAR(100) PRIMARY KEY,
    `value` TEXT,
    `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Affiliate networks tracking
CREATE TABLE `affiliate_networks` (
    `id` INT(11) AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(100) NOT NULL,
    `network_type` ENUM('amazon', 'shareasale', 'cj', 'impact', 'rakuten', 'other') DEFAULT 'other',
    `api_key` VARCHAR(255),
    `commission_rate` DECIMAL(5,2),
    `is_active` BOOLEAN DEFAULT TRUE
);

-- Insert default settings
INSERT INTO `settings` (`key`, `value`) VALUES
('site_name', 'GearGuide'),
('site_description', 'Expert reviews and buying guides for everything you love'),
('last_auto_update', NULL),
('last_blog_generation', NULL),
('total_auto_posts', '0'),
('total_products', '0'),
('total_clicks', '0'),
('total_earnings', '0');

-- Insert all 30+ categories
INSERT INTO `categories` (`name`, `slug`, `amazon_search_index`, `description`, `featured`, `display_order`) VALUES
-- Home & Living
('Coffee & Espresso', 'coffee-espresso', 'Kitchen', 'Premium coffee equipment and accessories for the perfect brew', 1, 1),
('Home Brewing', 'home-brewing', 'Kitchen', 'Beer and wine making supplies and accessories', 0, 2),
('Sous Vide', 'sous-vide', 'Kitchen', 'Precision cooking equipment and accessories', 0, 3),
('Air Fryers', 'air-fryers', 'Kitchen', 'Healthy frying accessories and replacement parts', 0, 4),
('Instant Pot', 'instant-pot', 'Kitchen', 'Multi-cooker accessories and replacement parts', 0, 5),
('Stand Mixers', 'stand-mixers', 'Kitchen', 'Attachments and accessories for stand mixers', 0, 6),
('Robot Vacuums', 'robot-vacuums', 'Electronics', 'Replacement parts and accessories for robot vacuums', 1, 7),
('Smart Home', 'smart-home', 'Electronics', 'Accessories for smart speakers, hubs, and devices', 0, 8),
('Air Purifiers', 'air-purifiers', 'HomeGarden', 'Replacement filters and accessories', 0, 9),

-- Fitness & Outdoors
('Home Gym', 'home-gym', 'Sports', 'Equipment and accessories for your home workout space', 1, 10),
('Treadmills', 'treadmills', 'Sports', 'Accessories and maintenance for treadmills', 0, 11),
('Exercise Bikes', 'exercise-bikes', 'Sports', 'Bike accessories, shoes, and replacement parts', 0, 12),
('Rowing Machines', 'rowing-machines', 'Sports', 'Rower accessories and maintenance', 0, 13),
('Camping', 'camping', 'OutdoorLiving', 'Tent, sleeping bag, and camping gear accessories', 1, 14),
('Hiking', 'hiking', 'OutdoorLiving', 'Backpack, boot, and hiking accessories', 0, 15),
('Kayaking', 'kayaking', 'OutdoorLiving', 'Kayak accessories, paddles, and safety gear', 0, 16),
('Electric Bikes', 'electric-bikes', 'Sports', 'E-bike accessories, batteries, and upgrades', 0, 17),
('Golf', 'golf', 'SportingGoods', 'Golf club accessories, bags, and training aids', 0, 18),
('Snow Sports', 'snow-sports', 'SportingGoods', 'Snowboard and ski accessories', 0, 19),

-- Pets
('Dogs', 'dogs', 'PetSupplies', 'Everything for your canine companion', 1, 20),
('Cats', 'cats', 'PetSupplies', 'Accessories and supplies for feline friends', 0, 21),
('Aquariums', 'aquariums', 'PetSupplies', 'Fish tank equipment and decorations', 0, 22),
('Small Pets', 'small-pets', 'PetSupplies', 'Supplies for rabbits, hamsters, and guinea pigs', 0, 23),
('Pet Tech', 'pet-tech', 'PetSupplies', 'GPS trackers, cameras, and smart pet devices', 0, 24),

-- Technology
('Gaming PCs', 'gaming-pcs', 'Electronics', 'Peripherals and upgrades for gaming computers', 1, 25),
('Gaming Consoles', 'gaming-consoles', 'VideoGames', 'Controller, headset, and console accessories', 1, 26),
('Steam Deck', 'steam-deck', 'VideoGames', 'Cases, docks, and accessories for handheld gaming', 0, 27),
('Tablets', 'tablets', 'Electronics', 'Cases, keyboards, and stylus accessories', 0, 28),
('Drones', 'drones', 'Electronics', 'Batteries, propellers, and drone accessories', 0, 29),
('Cameras', 'cameras', 'Camera', 'Lenses, tripods, bags, and photography gear', 1, 30),
('Smartwatches', 'smartwatches', 'Watches', 'Bands, screen protectors, and charging docks', 0, 31),
('Monitors', 'monitors', 'Electronics', 'Mounts, cables, and monitor accessories', 0, 32),

-- Automotive
('Car Accessories', 'car-accessories', 'Automotive', 'Floor mats, seat covers, and car upgrades', 1, 33),
('Baby Car Seats', 'baby-car-seats', 'Baby', 'Bases, accessories, and travel gear for car seats', 0, 34),
('Bicycles', 'bicycles', 'SportingGoods', 'Bike accessories, lights, and safety gear', 0, 35),
('Motorcycles', 'motorcycles', 'Automotive', 'Helmets, gloves, and motorcycle accessories', 0, 36),

-- Home Office
('Standing Desks', 'standing-desks', 'OfficeProducts', 'Mats, monitor arms, and desk accessories', 1, 37),
('Ergonomic Chairs', 'ergonomic-chairs', 'OfficeProducts', 'Cushions, arm pads, and chair upgrades', 0, 38),
('Laptop Accessories', 'laptop-accessories', 'Electronics', 'Docks, sleeves, and laptop cooling pads', 0, 39),

-- Baby & Kids
('Strollers', 'strollers', 'Baby', 'Cup holders, rain covers, and stroller accessories', 1, 40),
('Cribs', 'cribs', 'Baby', 'Mattresses, sheets, and crib accessories', 0, 41),
('Baby Monitors', 'baby-monitors', 'Baby', 'Extra cameras, mounts, and monitor accessories', 0, 42),
('High Chairs', 'high-chairs', 'Baby', 'Cushions, tray covers, and high chair accessories', 0, 43),

-- Hobbies
('3D Printing', '3d-printing', 'Industrial', 'Filament, build plates, and printer upgrades', 1, 44),
('Sewing', 'sewing', 'ArtsAndCrafts', 'Thread, needles, and sewing machine accessories', 0, 45),
('Vinyl Cutting', 'vinyl-cutting', 'ArtsAndCrafts', 'Vinyl sheets, tools, and cutter accessories', 0, 46),
('Musical Instruments', 'musical-instruments', 'MusicalInstruments', 'Cases, stands, and instrument accessories', 0, 47);

-- Insert subcategories for major categories
INSERT INTO `subcategories` (`name`, `slug`, `category_id`, `description`) VALUES
-- Coffee subcategories
('Espresso Machines', 'espresso-machines', (SELECT id FROM categories WHERE slug = 'coffee-espresso'), 'Accessories for espresso machine owners'),
('Pour Over', 'pour-over', (SELECT id FROM categories WHERE slug = 'coffee-espresso'), 'Pour over coffee accessories'),
('French Press', 'french-press', (SELECT id FROM categories WHERE slug = 'coffee-espresso'), 'French press accessories and replacement parts'),
('Coffee Grinders', 'coffee-grinders', (SELECT id FROM categories WHERE slug = 'coffee-espresso'), 'Grinder accessories and cleaning supplies'),

-- Home Gym subcategories
('Weightlifting', 'weightlifting', (SELECT id FROM categories WHERE slug = 'home-gym'), 'Barbells, plates, and weightlifting accessories'),
('Cardio Equipment', 'cardio-equipment', (SELECT id FROM categories WHERE slug = 'home-gym'), 'Treadmill, bike, and rower accessories'),
('Flooring', 'flooring', (SELECT id FROM categories WHERE slug = 'home-gym'), 'Gym mats, tiles, and floor protection'),
('Storage', 'storage', (SELECT id FROM categories WHERE slug = 'home-gym'), 'Weight racks, wall mounts, and organization'),

-- Dogs subcategories
('Crates & Kennels', 'crates-kennels', (SELECT id FROM categories WHERE slug = 'dogs'), 'Crate accessories, beds, and covers'),
('Training', 'training', (SELECT id FROM categories WHERE slug = 'dogs'), 'Training collars, clickers, and treats'),
('Grooming', 'grooming', (SELECT id FROM categories WHERE slug = 'dogs'), 'Brushes, shampoos, and grooming tools'),
('Walking', 'walking', (SELECT id FROM categories WHERE slug = 'dogs'), 'Leashes, harnesses, and poop bag holders'),

-- Gaming subcategories
('Controllers', 'controllers', (SELECT id FROM categories WHERE slug = 'gaming-consoles'), 'Replacement and pro controllers'),
('Headsets', 'headsets', (SELECT id FROM categories WHERE slug = 'gaming-consoles'), 'Gaming headsets and audio accessories'),
('Charging', 'charging', (SELECT id FROM categories WHERE slug = 'gaming-consoles'), 'Charging docks and battery packs'),
('Protection', 'protection', (SELECT id FROM categories WHERE slug = 'gaming-consoles'), 'Console skins, cases, and screen protectors'),

-- Camping subcategories
('Tents', 'tents', (SELECT id FROM categories WHERE slug = 'camping'), 'Tent accessories, stakes, and footprint'),
('Sleeping', 'sleeping', (SELECT id FROM categories WHERE slug = 'camping'), 'Sleeping bags, pads, and pillows'),
('Cooking', 'cooking', (SELECT id FROM categories WHERE slug = 'camping'), 'Camp stoves, cookware, and utensils'),
('Lighting', 'lighting', (SELECT id FROM categories WHERE slug = 'camping'), 'Lanterns, headlamps, and flashlights');